package com.kozka.hospitaldepartment.entities;

/**
 * @author Kozka Ivan
 */
public enum Specialization {
    ALLERGIST, ANESTHETIST, REANIMATOLOGIST,
    EPIDEMIOLOGIST, CARDIOLOGIST, ONCOLOGIST,
    TRAUMATOLOGIST, ORTHOPEDIST, PHYSIOTHERAPIST,
    RADIOLOGIST, TOXICOLOGIST, PULMONOLOG, UROLOGIST,
    THERAPIST, PEDIATRICIAN, INFECTIONIST, SURGEON,
    GYNECOLOGIST, NEUROPATHOLOGIST, PSYCHIATRIST,
    NARCOLOGIST, OPHTHALMOLOGIST, OTOLARYNGOLOGIST,
    DERMATOVENEROLOGIST, DENTIST, FAMILY_DOC
}
